### ISSUE TITLE
Stuck on splash screen

### ISSUE THREAD

**Issue by MahdiGhiasi** [MahdiGhiasi/Xpotify#104]
On some devices, Xpo Music v3 Preview gets stuck on splash screen, not showing anything. This might be an external bug with WebView control, as a user reported that after changing Edge version on their PC, the problem vanished.

Still needs more investigation.

**Comment by MahdiGhiasi** [comment]
With help of UWP Community discord users, we figured out that WebView2 in WinUI 3 needs beta version of Edge installed, and does not work with public version.

**Comment by LSeelig** [comment]
This is still happening to me. I'm on Edge 86, but doesn't web view still use the old Edge?

**Comment by MahdiGhiasi** [comment]
@LordMethenor This issue was for the vNext version prototype, using WebVIew2. However, currently the stable version of the app suffers from same thing, due to Spotify PWA dropping support of Edge Legacy. You can follow its status at #112.
