### ISSUE TITLE
Windows arm64 support

### ISSUE THREAD

**Issue by mirogl** [MahdiGhiasi/Xpotify#105]
Hi
I tried today your app on my Surface Pro X with Windows arm64. In the Tak Manager the application is still shown as 32-bit, but in the Windows Store arm64 support is documented also as an Option in Visual Studio 2019.

Therefore - is Windows arm64 currently supported and the apps runs native or why is the app showing as 32-bit ?

Thanks
Miro

**Comment by MahdiGhiasi** [comment]
Xpo Music had some crashing issues with arm64, so that build is not yet present. 

However, Xpo Music has a 32-bit arm binary present, so while you're seeing it as 32-bit on Surface Pro X, it's *not* using x86-to-arm emulation.
