### ISSUE TITLE
(Question) Settings tab? streaming quality?

### ISSUE THREAD

**Issue by Appex213** [MahdiGhiasi/Xpotify#108]
Just wanted to ask where is the settings tab (or if it's even implemented yet), and what is the default streaming quality?

**Comment by MahdiGhiasi** [comment]
Settings is available on the bottom-left corner of the app. However, if you're talking about the next preview version of Xpo Music, settings is not implemented in that version yet.

Regarding streaming quality, Xpo Music (and Spotify Web, which Xpo Music uses) only offer one setting: AAC 256kbit/s for Premium users and AAC 128kbit/s for Free users.
