### ISSUE TITLE
xpotify.ghiasi.net does not resolve

### ISSUE THREAD

**Issue by hischampion** [MahdiGhiasi/Xpotify#11]
When I try to log in with my Spotify account, everything works until I get this screen saying "NotFound" for the URL to activate Xpotify with Spotify's API. 

I copied the URL and went to it, but when it redirects, I get this 
![image](https://user-images.githubusercontent.com/17257786/59128110-f771d480-891d-11e9-8022-0430adf207b9.png)

Seems like something that could block others from signing up in the app.

**Comment by MahdiGhiasi** [comment]
It shouldn't matter for the sign in process, as the app goes through with the URI on WebView's failed handler as well.

But there has been several reports of seeing NotFound screen after logging in, and I have no clue why this is happening at the moment.

**Comment by MahdiGhiasi** [comment]
I've fixed the server-side issue of xpotify.ghiasi.net returning not found, just in case the logic for WebView's failed handler does not work properly sometimes for some unknown reason.

@hischampion Can you check if this still happens on the Xpotify app for you?
