### ISSUE TITLE
Option to hide song/artist

### ISSUE THREAD

**Issue by pepijnmm** [MahdiGhiasi/Xpotify#12]
There is already an option to hide a song or artist in the windows version. Would be great is it would also be possible through Xpotify.
picture Release Radar(this option is only for discover weekly, Daily mix and release radar):
![image](https://user-images.githubusercontent.com/3217184/59136353-fde66780-8982-11e9-9361-730e96941315.png)

Xpotify(only possible in Daily mix):
![image](https://user-images.githubusercontent.com/3217184/59137549-9f23ec80-8988-11e9-94b1-d320f6f4b1a0.png)
But on discover and Release I only see the heart

**Comment by MahdiGhiasi** [comment]
This can only be done by Spotify on their PWA. Will close this for now.
