### ISSUE TITLE
Split script and css files to multiple files and compile them to one.

### ISSUE THREAD

**Issue by MahdiGhiasi** [MahdiGhiasi/Xpotify#13]
`initScript.js`, `initLightTheme.js`, `style.css` and `style-light.css` files are becoming too big, and ugly to remember all the details and maintain them.

We should split those files into many files, each handling one specific functionality. Then we can either compile them all to one script on each release (on development time), or stitch them together on runtime, maybe.

Note: Remember to explore existing solutions for this type of situation.

**Comment by BenConstable9** [comment]
Could explore developing the CSS with SASS with a different style sheet for each section and then importing and compiling into one upon release. Unfortunately might require a large amount of work.

**Comment by MahdiGhiasi** [comment]
And the JavaScript can be separated into different files and then imported and compiled into one with TypeScript.

**Comment by MahdiGhiasi** [comment]
This is done using TypeScript and SASS.
