### ISSUE TITLE
Explore using Spotify Playback SDK for premium users

### ISSUE THREAD

**Issue by MahdiGhiasi** [MahdiGhiasi/Xpotify#14]
Currently Xpotify lets the PWA handle music playback. Using [Spotify Playback SDK](https://developer.spotify.com/documentation/web-playback-sdk) might be a good alternative. 

Possible advantages are:

* Maybe more reliable than the PWA on MS Edge
* The app can be listed as "Xpotify" in Spotify Connect, instead of "Web Player (Microsoft Edge)"

For free users, we can continue using the PWA.

If we ever implement this, we should keep both options available for premium users to choose.

**Comment by hansmbakker** [comment]
Maybe this also allows for higher bitrate playback for premium users? I thought that if you play via the web then they limit the bitrate.

**Comment by MahdiGhiasi** [comment]
@hansmbakker It seems that the Web Player SDK [also uses 256kbps](https://community.spotify.com/t5/Other-Partners-Web-Player-etc/Bitrate-for-the-new-WEB-PLAYBACK-SDK/td-p/3536619), unfortunately.

However, the 256kbps that the Web Player SDK and Web App have seem to be a different audio encoding than the 320kbps one that desktop/mobile apps use, so they're not directly comparable.

**Comment by MahdiGhiasi** [comment]
The Web Player SDK uses the same tech as the PWA, so the reliability issues are present there. They only gain seem to be having the correct name in Spotify Connect.

**Comment by MahdiGhiasi** [comment]
As this is requires a lot of work, but gives little gain, I choose not to do this at the moment.
