### ISSUE TITLE
Unable to sign-in

### ISSUE THREAD

**Issue by Werror** [MahdiGhiasi/Xpotify#15]
I have obtained the developer ID and secret, however, when I am at the sign-in page, after inputting the correct credential, I get, "Invalid redirect URI" error, same with creating a new account.

**Comment by Werror** [comment]
![image](https://user-images.githubusercontent.com/9371636/59222124-c8b26300-8b96-11e9-91e9-230b15ec1de0.png)

**Comment by MahdiGhiasi** [comment]
I'm sorry, I should've added this to the "How to build" section.

You need to define a Redirect URI in the settings of your created entry in Spotify dashboard as well. 

You can either set the Redirect URI in Spotify dashboard to `https://xpotify.ghiasi.net/login/redirect`, or set it to something else and then also modify [this line of code](https://github.com/MahdiGhiasi/Xpotify/blob/7e003b9879104a5b8b771f48475feca92155de8a/Xpotify/SpotifyApi/Authorization.cs#L18) accordingly.

**Comment by Werror** [comment]
Thank you so much for the quick response, this is amazing!!!!
