### ISSUE TITLE
Show alert when adding a song to the playlist which is already there

### ISSUE THREAD

**Issue by supermartzin** [MahdiGhiasi/Xpotify#22]
When I am adding some song to one of my playlists, it doesn't show a warning about a **duplicate song**, as the official Spotify app, it will automatically add the song to the playlist multiple times.

![duplicate-song](https://user-images.githubusercontent.com/6864050/59787770-7e359280-92ca-11e9-885c-70921a628ccb.png)

I think this should be done the same way as in the Spotify app, **ask each time for confirmation**.

**Comment by MahdiGhiasi** [comment]
As this is handled in the Spotify PWA logic itself, overriding it is not easy and will be prone to breaking with changes from the PWA side. So we can't implement this properly on Xpo.

It's a good idea to send this feedback to the Spotify team though, as they can easily add this to the PWA (and Xpo)
