### ISSUE TITLE
"Listening on" client name in Spotify

### ISSUE THREAD

**Issue by ajmeese7** [MahdiGhiasi/Xpotify#29]
When I am listening to Xpotify, the regular Spotify client says this:

![image](https://user-images.githubusercontent.com/17814535/60770705-b2b79580-a0a3-11e9-9814-3c65a512c917.png)

Is it possible to change this to Xpotify or something more representative than "Web Player (Microsoft Edge)?" I am unfamiliar with the Spotify Developer API so I wouldn't know where to start.

**Comment by MahdiGhiasi** [comment]
Spotify PWA registers itself with this name, and I couldn't find a way to change it. (Not even in the requests being sent by the PWA)

The only way I can think of is using Web Playback SDK instead of the PWA (#14), which needs a massive effort but gains so little; so I decided to skip it for now.

If anyone knows an easier way of changing this, please ping me.

**Comment by MahdiGhiasi** [comment]
Good news, I actually found a way of changing that name by modifying a request on the fly. 

Hopefully this will be available on the next release.

**Comment by MahdiGhiasi** [comment]
... and it's done!

<img src="https://user-images.githubusercontent.com/1775637/60834980-3faf3b80-a1d7-11e9-82cf-8237ff1dc6fe.png" width="200px" />

**Comment by ajmeese7** [comment]
👍 keep me updated. I'd appreciate it if you can leave a comment on the issue once it is merged

**Comment by MahdiGhiasi** [comment]
It's already merged to master. ([This commit](https://github.com/MahdiGhiasi/Xpotify/commit/6f6e284b7eceec1cbaa0fb9d2f499b8a71890650)) 

Although it'll probably need a bit more testing to make sure it always works properly, so I'm keeping the issue open for now.

**Comment by ajmeese7** [comment]
I was meaning more when it is available on the Windows Store app. I just purchased pro to support the development of this amazing app, because it is refreshing to make an issue on a project and to have the feature added within a day. Keep up the great work 🎉
