### ISSUE TITLE
Cannot save proxy setting

### ISSUE THREAD

**Issue by dmaglio** [MahdiGhiasi/Xpotify#3]
If i write my proxy url, when i click to apply setting the InputText turn empty

**Comment by MahdiGhiasi** [comment]
Can you please tell me the URL you're typing into the text box?

**Comment by dmaglio** [comment]
Http://user:pwd@domain

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by Sinaxx** [comment]
i've got the same problem. and can add support for user name and password for proxies

**Comment by MahdiGhiasi** [comment]
There's a bug in the latest version causing the text box to become empty, but it should not still apply, if you don't touch the textbox right after the text disappears. (I've already fixed the bug, but not yet on the store)

@dmaglio @Sinaxx Can you remove the `http://` part and type `user:pwd@domain.com` into the box, and see if that works?
