### ISSUE TITLE
user-top-read scope bug

### ISSUE THREAD

**Issue by mgoulao** [MahdiGhiasi/Xpotify#30]
With user-top-read scope the API responds with a status of 404. [Spotify Web API bug](https://github.com/spotify/web-api/issues/1262)

Remove it seems to fix the problem.

**Comment by MahdiGhiasi** [comment]
Which APIs are returning 404 for you?

**Comment by mgoulao** [comment]
The Spotify Web API when obtaining authorization.  [https://github.com/MahdiGhiasi/Xpotify/blob/master/Xpotify/SpotifyApi/Authorization.cs](https://github.com/MahdiGhiasi/Xpotify/blob/master/Xpotify/SpotifyApi/Authorization.cs)

**Comment by MahdiGhiasi** [comment]
It seems that Spotify has [solved this issue](https://github.com/spotify/web-api/issues/1262#issuecomment-511206677), so I'm closing this.
