### ISSUE TITLE
Why is it not avaible in the Microsoft Store?

### ISSUE THREAD

**Issue by PaulolifeBR** [MahdiGhiasi/Xpotify#33]

**Comment by JacobValdemar** [comment]
It already is, check [here](https://www.microsoft.com/store/productId/9N1N68MC7FXR)

**Comment by mike-mo** [comment]
![image](https://user-images.githubusercontent.com/464024/60929222-513f2480-a265-11e9-9c29-ccf9c0a73b24.png)

**Comment by PaulolifeBR** [comment]
As Mike posted, it is avaible only using a code, and I cannot see anywhere i can get it.

**Comment by tenpaiyomi** [comment]
Adding to this, showing up for me as not available as well.

**Comment by MarcoVdE** [comment]
Seems because it's US only, can't access from South Africa.

**Comment by MahdiGhiasi** [comment]
Xpotify is currently unavailable from the Store because of some issues regarding its name with Spotify's branding guidelines.

I'm trying to solve the issues (a name change might be necessary) and republish it as soon as possible.

**Comment by tenpaiyomi** [comment]
Definitely not US only. I'm in the US and could not access it.

**Comment by MarcoVdE** [comment]
@tenpaiyomi I mean it's not even listed rather than a redeem code button.

**Comment by tenpaiyomi** [comment]
@marcoValkyriweb Ah ok, I gotcha now

**Comment by Psiphonc** [comment]
the same issue happens to me

**Comment by gschurck** [comment]
Can you add a release on github to be able to download the software while it's not on microsoft store ?

**Comment by penniesfromheaven** [comment]
> Can you add a release on github to be able to download the software while it's not on microsoft store ?

This would be much appreciated even if the issues with Microsoft are resolved.

**Comment by Hiephnp** [comment]
Where can I get the redeem code?

**Comment by MahdiGhiasi** [comment]
Xpotify is now renamed to Xpo Music and is back on the Microsoft Store!
