### ISSUE TITLE
Songs consistently play twice

### ISSUE THREAD

**Issue by JacobValdemar** [MahdiGhiasi/Xpotify#34]
**Summary**
When playing a playlist every song will be played two times before continuing to the next song.

**Steps to reproduce**
1. Find a playlist created by Spotify (e.g. a national top 50 chart).
2. Point your cursor at the playlist
3. Click the big play button
4. Keep listening for several songs

**Expected behavior**
Every song will only be played one

**Notes**
Some times the app will skip several songs at a time when it has finished a song. E.g. skipping 3 songs.
It should be noted, that this happened during a Discord "listening together"

**Comment by MahdiGhiasi** [comment]
Can you please check whether this still happening for you on v2.0?

**Comment by JacobValdemar** [comment]
Apparently it don't happen anymore
