### ISSUE TITLE
Application crashing on start

### ISSUE THREAD

**Issue by LuCiAn0** [MahdiGhiasi/Xpotify#36]
After the application was renamed to Xpo, I re-installed it through MS store and now it crashes on start. I tried removing all files related to it and re-installing but I'm still getting the same issue. 
It loads the splash screen then crashes right after.

**Comment by MahdiGhiasi** [comment]
What is your OS version?

**Comment by MahdiGhiasi** [comment]
There has been a bug causing crash on some versions (likely 1803 or below, but I didn't have a 1809 machine to test). It has been fixed now and a hotfix is published to the Store (v2.0.1), please update the app and see if that solves the issue you're facing.

**Comment by LuCiAn0** [comment]
Hi @MahdiGhiasi .. updating it to version 2.0.1.0 fixed the issue. Thank you so much!
