### ISSUE TITLE
Can't Download Xpo Music

### ISSUE THREAD

**Issue by zlyfer** [MahdiGhiasi/Xpotify#37]
When trying to download Xpo Music I get the error:
0x80072EFD - Check Internet Connection

Quick search said that it might be an IPv6 problem but I have a stable & fast IPv4 and IPv6 connection. I tried test downloading other apps like Netlix, etc. and they downloaded correctly and without errors.

My Windows 10 Version: 1903 (Build 18362.239)

**Comment by zlyfer** [comment]
Nevermind it got fixed automatically. Sorry.

**Comment by MahdiGhiasi** [comment]
Glad it got fixed :)
