### ISSUE TITLE
Remember View where you have left

### ISSUE THREAD

**Issue by crstmkt** [MahdiGhiasi/Xpotify#38]
When I leave the "Library"-Page where I was on on the "Albums"-View to go to the "Start Page" and Then back to the "Library"-Page, I would like to get back on the "Albums"-View automatically, because it was the last View I visited on the "Library"-Page.

**Comment by crstmkt** [comment]
Additionally: When I'm on the "Albums"-View and have scrolled down for example half the way, then click on an Album and then Back in the top left corner I will get back to the top of the "Albums"-View. It would be great if I'll get back to where I was on the "Albums"-View (Half the way down).

**Comment by MahdiGhiasi** [comment]
This should work now.
