### ISSUE TITLE
Liked song message displays strangely

### ISSUE THREAD

**Issue by ajmeese7** [MahdiGhiasi/Xpotify#41]
As shown below, in Xpo, the liked song message is centered in just the right panel and is much longer than the message it contains. The box is also very short and is positioned a good bit above the play bar.

![image](https://user-images.githubusercontent.com/17814535/61965717-80a89d80-af96-11e9-90ec-4ccd04a05e94.png)

In the Spotify client, the message is centered on the window and the box's height and width are much more proportional to the message it contains. It is also positioned much closer to the play bar, maybe even too close.

![image](https://user-images.githubusercontent.com/17814535/61965756-9f0e9900-af96-11e9-8d0a-f14a547866d8.png)

It would be nice if the Xpo version could be turned into a better version of the Spotify message, because right now it isn't very visually appealing. It's worth mentioning that the issue is present with all similar messages, such as adding to a playlist or removing a like, not just liking a song.

Also, when I was getting these screenshots, I noticed that the Spotify UI updated instantly when I liked the song in Xpo, but the Xpo client would not change to reflect whether I liked or removed a like from the song in Spotify. Is it possible to fix this with some listener code for changes made in Spotify?

**Comment by MahdiGhiasi** [comment]
Previously this message appeared as a green bar on top of the window, and Xpo Music applied some custom CSS to make it look better. 

They (Spotify PWA) have since changed it to this blue box on the bottom. It's likely that the modification is making the box look bad here, and also in the PWA itself the box is not centered as well, so that's a bug on them.

So we're gonna have to 1. remove the wrong CSS modifications 2. add new CSS rules to make the blue box centered.

**Comment by MahdiGhiasi** [comment]
> Also, when I was getting these screenshots, I noticed that the Spotify UI updated instantly when I liked the song in Xpo, but the Xpo client would not change to reflect whether I liked or removed a like from the song in Spotify. Is it possible to fix this with some listener code for changes made in Spotify?

About this, I don't think there's a listener API from Spotify to listen for these changes, and then also the UI for that is handled by the PWA itself, which presents another problem even if we detect the change.

**Comment by ajmeese7** [comment]
@MahdiGhiasi would you like me to create a separate issue for that to make it easier to track in the future instead of having it tied in with this one? There has to be some way of doing it since the Spotify client does it from our app, but they probably just haven't made it public yet or we haven't found it. Might be worth waiting and looking into it another time.

**Comment by MahdiGhiasi** [comment]
@ajmeese7 Yes, please create a separate issue for that.

The issue described in this page is fixed and will be available in the next update.
