### ISSUE TITLE
Several references to Xpotify throughout project

### ISSUE THREAD

**Issue by ajmeese7** [MahdiGhiasi/Xpotify#42]
Since the rename, the only real modification to reflect references to the old name was 5c87789de653a3c6b6b6185dee86ce45666d6455, but even the README update didn't change Xpotify references to Xpo Music other than in the header.

Throughout the file structure as well, there are many things including the primary folder that are named Xpotify. Are you wanting someone to work on changing this, or does it not matter to you? I wouldn't mind attempting the refactor if you consider this an issue. Just not sure what all you had to change as a result of the issue with the project name.

**Comment by MahdiGhiasi** [comment]
The remaining references to Xpotify is now renamed to XpoMusic. (currently in the development branch)
