### ISSUE TITLE
[Request] Make the App Startup with Windows 

### ISSUE THREAD

**Issue by kramseyking** [MahdiGhiasi/Xpotify#48]

**Comment by MahdiGhiasi** [comment]
UWP apps can't reliably open on startup (they can, but it'll be minimized). So I'm skipping this for now.

**Comment by lieuweberg** [comment]
Would like to note that this is wanted behavior (the minimizing) for probably a majority of users, I personally just use my media keys to navigate my playlist and when I actually need Spotify I click it, way better than having to open it each time you just want to continue the music.
