### ISSUE TITLE
[Request] Mini player, save to liked songs should be a visible plus or heart

### ISSUE THREAD

**Issue by ziplock9000** [MahdiGhiasi/Xpotify#50]
You should be able to see at a glance if the current song is a favourite rather than having to click the ellipsis and seeing if the menu option is there for "Save to your liked songs"
This is the philosophy that Spotify uses and it works quite well and means no digging into menus is needed.

**Comment by eddieparker** [comment]
Totally agree.  Similarly, a "dislike" on the opposite side of where the heart is would be ideal.

**Comment by MahdiGhiasi** [comment]
This is possible if you make mini view slightly larger. For the smaller version of mini view, keeping the layout as clean as possible is the priority.

![image](https://user-images.githubusercontent.com/1775637/82465885-015ff980-9ad5-11ea-8646-f6024ace88f4.png)
