### ISSUE TITLE
[Request] Do not limit mini-player size

### ISSUE THREAD

**Issue by ScottBeeson** [MahdiGhiasi/Xpotify#51]
I LOVE the mini player feature.  I have a monitor on the back wall of my office that I use almost exclusively for Spotify full screen.  With Xpo I like the look of the mini player better, but I wish I could make it bigger so I could read the text, etc.

Alternatively, make a full-screen player!

**Comment by PhilLB1239** [comment]
Didn't Xpo Music also comes with a Now Playing page with the 2V update?
![image](https://user-images.githubusercontent.com/51797038/62312022-19d62900-b45b-11e9-8e44-4afae8182dca.png)

**Comment by MahdiGhiasi** [comment]
Xpo Music does contain a full-screen player. Click on "Now Playing" on the side bar to open it.

![image](https://user-images.githubusercontent.com/1775637/62390507-bb529d00-b577-11e9-8850-7f0036d36b90.png)

**Comment by ScottBeeson** [comment]
A little unintuitive, but awesome. Thanks!
