### ISSUE TITLE
Player sometimes skips songs

### ISSUE THREAD

**Issue by Matipolit** [MahdiGhiasi/Xpotify#53]
Sometimes when playing music the player skips one or more tracks (version 2.0.3.0)

**Comment by LuminarySage** [comment]
I get this issue too. Accompanying it sometimes is a random pause right after it skipped

**Comment by MahdiGhiasi** [comment]
This is a bug with Spotify PWA on Edge (now Legacy). Xpo Music tries to avoid freezing playback, which can sometimes lead to skipping songs.

Maybe when WebView2 is available, this will be fixed automatically.

I'm closing this issue for now.
