### ISSUE TITLE
Styling in search page breaks layout

### ISSUE THREAD

**Issue by stockhuman** [MahdiGhiasi/Xpotify#54]
![5e179484b93bf849bb6f8ba21b7e95dc](https://user-images.githubusercontent.com/13852458/62428879-64270680-b6f6-11e9-9b8e-e78473172737.jpg)

As pictured, search results overlay the now-playing bar

OS: Windows 10 (1903) on a 4K display (DPI scaling @ 1.5)

Thanks!

**Comment by rahmanrafi** [comment]
Same issue with the light theme as well. Windows 10 1903 running version 2.0.5.0.

![image](https://user-images.githubusercontent.com/7981565/63537088-f2ff9580-c4e2-11e9-9c31-499be20629d0.png)
