### ISSUE TITLE
Font smoothing?

### ISSUE THREAD

**Issue by brgkode** [MahdiGhiasi/Xpotify#55]
Font smoothing/anti-aliasing seems to be nonexistent. Attached image with Xpo on the left Spotify on the right for comparison, running on windows 10 1903 on a 1080p screen.
![image](https://user-images.githubusercontent.com/29178652/62871644-27719580-bd1c-11e9-95f1-45eace0ef1d5.png)

**Comment by MahdiGhiasi** [comment]
I've looked into it, and it seems that EdgeHTML should have the antialiasing enabled by default (and there's no way to disable it, it seems).

You can try calibrating your ClearType configuration by typing "Adjust ClearType" in the taskbar search.
