### ISSUE TITLE
Listener for changes in Spotify

### ISSUE THREAD

**Issue by ajmeese7** [MahdiGhiasi/Xpotify#56]
The Spotify UI updates instantly when I like a song in Xpo, but the Xpo client does not change to reflect whether I liked or removed a like from the song in Spotify. Is it possible to fix this with some listener code for changes made in Spotify?

Made because requested in #41.

**Comment by MahdiGhiasi** [comment]
Spotify PWA (which Xpo Music uses) doesn't listen for changes. Doing so would be expensive (you basically have to poll the API), and also would need manipulation of Spotify PWA UI elements, which is hacky and can easily break with PWA updates.

So, unless the PWA itself adds something like this, I don't think I can add this to Xpo Music.
