### ISSUE TITLE
[Request] Import music from hard drive

### ISSUE THREAD

**Issue by imaandrew** [MahdiGhiasi/Xpotify#61]
I would really find it useful if you were able to add music from your hard drive into your liked songs or another playlist. I have lots of songs in my music folder that aren't on spotify and it would be great if they were all in one place.

**Comment by LuminarySage** [comment]
I don't think this is possible. Only the official desktop Spotify app can add local tracks to your account. Even the mobile app can't

**Comment by sorzcode** [comment]
what about playing local files? I created a playlist with local files on the official spotify windows app and I want to play the playlist on Xpotify. Is this also not possible? coz i can't see the option to make the playlist offline in this app

**Comment by LuminarySage** [comment]
It's based on the Spotify PWA so anything you can and can't do on that applies to Xpotify/XpoMusic

**Comment by LuminarySage** [comment]
This is the PWA btw https://open.spotify.com/
