### ISSUE TITLE
Mini view is always on top

### ISSUE THREAD

**Issue by Anachronaut** [MahdiGhiasi/Xpotify#65]
Wondering if there's a way to implement a toggle for always-on-top for Mini View?

**Comment by LuminarySage** [comment]
You want to toggle it off, right? Cuz it's already always on top in mini view

**Comment by Anachronaut** [comment]
Correct

**Comment by MahdiGhiasi** [comment]
Mini view is always on top by design. Now Playing page offers a similar experience without being on top.
