### ISSUE TITLE
Light Theme turns everything negative

### ISSUE THREAD

**Issue by JTDaddy17** [MahdiGhiasi/Xpotify#70]
The light theme mode in Xpo Music turns all the album images and other elements negative, like a negative photograph, in dark mode the app looks fine but light mode looks... creepy... not sure if something needs to be updated but please fix this. 
![Annotation 2019-11-12 201037](https://user-images.githubusercontent.com/50080776/68724117-a16a2280-0588-11ea-8794-e97f6df02449.jpg)

**Comment by LuminarySage** [comment]
Yeah I also got that too but that has to be a bug in one of the recent versions because I have never encountered this before with light theme on
![image](https://user-images.githubusercontent.com/24306400/68826192-d2bb1f00-066a-11ea-9a32-f2b48a3bf8e7.png)

**Comment by LuminarySage** [comment]
I think it's fixed

@MahdiGhiasi I think you should mark issues as solved if they are fixed to prevent clutter in the Issues page

**Comment by JTDaddy17** [comment]
Yep, its fixed, thanks!

**Comment by LuminarySage** [comment]
This bug is showing up again...

![image](https://user-images.githubusercontent.com/24306400/70094965-9b98b780-15f1-11ea-97f5-e0aad3f6469b.png)
