### ISSUE TITLE
Back button on mouse does not work

### ISSUE THREAD

**Issue by jevandezande** [MahdiGhiasi/Xpotify#73]
The back button on my mouse does nothing. I would expect it to go back to the previous screen, performing the same action as the back button in the top left corner. Making the forward button on the mouse work would also be great, but I imagine would take a lot more work.

**Comment by MahdiGhiasi** [comment]
There's currently no way of detecting back button on `WebView` control, neither from inside the control nor from the UWP-side. So while this is known, I can't fix this at the moment.
