### ISSUE TITLE
404 and more errors

### ISSUE THREAD

**Issue by semrocc** [MahdiGhiasi/Xpotify#74]
The Xpo Music app is showing some errors as of recent. Opening the app, it starts as a 404 Not Found page, followed by a popup message with other errors present.
![error-1](https://user-images.githubusercontent.com/5757014/70583796-6c032580-1b84-11ea-86bb-d2236097d974.jpg)
![error-2](https://user-images.githubusercontent.com/5757014/70583802-6f96ac80-1b84-11ea-93b9-67d35f869f19.jpg)

**Comment by coucourou** [comment]
me too.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/51652498/70626152-db4d4800-1c5e-11ea-9164-9d51caae151c.png)
it says that "Sorry, we could't find it" and return a web page of Spotify web player.
