### ISSUE TITLE
[Request] Add shadow in Now Playing Controller and options to download high quality artist art

### ISSUE THREAD

**Issue by berlaychen** [MahdiGhiasi/Xpotify#79]
Hello, i have some recommend:

1. Add Gradient Shadow or blurry for controller in now playing, just like this
![image](https://user-images.githubusercontent.com/51433626/71824362-5544e580-30d4-11ea-86ed-7c50ce18c4c8.png)
So user can see controller easily.

2. Some artist art is low quality

thanks for great work

**Comment by MahdiGhiasi** [comment]
Thanks for the UI suggestion.

About the artist arts, the highest quality art available via Spotify API is currently used, which might be low quality in some cases.

I couldn't find other ways to find artist arts reliably and easily, but assuming there is, it can be done sometime.

For now, I'm closing this issue.
