### ISSUE TITLE
Facebook login flow is broken

### ISSUE THREAD

**Issue by trinhdhk** [MahdiGhiasi/Xpotify#80]
Spotify PWA changed URL from web.spotify.com to open.spotify.com, led app to be soft broken.

**Comment by MahdiGhiasi** [comment]
Xpo Music has been always opening open.spotify.com since the beginning, and is currently loading properly here.

Can you explain more what behavior and error message (if any) are you seeing when you open Xpo Music?

**Comment by trinhdhk** [comment]
Sorry I didn't know that. Currently it redirects to accounts.spotify.com.

**Comment by MahdiGhiasi** [comment]
Do you see the login screen? If so, are you able to access Spotify PWA after logging in?

**Comment by MahdiGhiasi** [comment]
Oh, I was able to reproduce this by logging out and logging back in. Will see what I can do.

**Comment by trinhdhk** [comment]
Many thanks. Your app is so great.

**Comment by MahdiGhiasi** [comment]
The issue seem to affect Facebook users only (user/pass login is working properly)

I've updated the issue title, currently working on a fix.

**Comment by MahdiGhiasi** [comment]
A server-side hotfix is now deployed for this issue. The Facebook login flow should work properly now.
