### ISSUE TITLE
Scrollbar covers area not scrolled

### ISSUE THREAD

**Issue by ajmeese7** [MahdiGhiasi/Xpotify#82]
I don't know if this is a style choice or an accident, but the scroll bar goes up by `Create Playlist` and `Liked Songs` even though those are not scrolled with the rest of the content.

![image](https://user-images.githubusercontent.com/17814535/74095084-3362c800-4ab1-11ea-8572-54032c1f98ef.png)

Also, it would be helpful if there was another `<hr>` at the bottom of the scrollbar area so we can see where the playlists stop and the `Settings` section begins. Kinda like actual Spotify does with theirs:

![image](https://user-images.githubusercontent.com/17814535/74095139-21355980-4ab2-11ea-80cd-7cd75efee9ac.png)

I also like how that one is 100% width, making it easy to differentiate from the section that has the scrollbar where it's only like 90% width. But this is a matter of opinion, so if you disagree with my thoughts on that feel free to shut me down.

<hr>

By the way, hi again! Just came back to this project after a while away and I'm glad I supported the development. You've made a lot of improvements and I'm extremely satisfied with the project. Is there a way we can donate even after purchasing premium to continue to show support?

**Comment by MahdiGhiasi** [comment]
Thanks for the report, the scrollbar position should be fixed on the recent over-the-air update :)
