### ISSUE TITLE
"Enable secure playback in your browser" prompt suddenly

### ISSUE THREAD

**Issue by Onoitsu2** [MahdiGhiasi/Xpotify#86]
I've been using this for a few weeks now, and not had any really major issues, occasionally having to re-launch it because it gets stuck, but that's what happens with a progress web app at times. But now, today, with no other changes I am seeing issues playing music in the app, seeing this message. 

attached is a screen capture of how it shows in the app.

![image](https://user-images.githubusercontent.com/4420175/75726002-c4872200-5c9e-11ea-9b0c-9ab51586868f.png)

**Comment by cameronkelley** [comment]
Same issue here

**Comment by MahdiGhiasi** [comment]
Can you please check if the 'Media Licenses' is enabled on the 'Privacy and Security' section of Edge Legacy settings?

![image](https://user-images.githubusercontent.com/1775637/77935796-2bf8b780-72c7-11ea-85a6-1a9c286e7651.png)

**Comment by Onoitsu2** [comment]
Confirmed, that is enabled on mine, however I'm unsure as to what Edge's settings have to do with the UWP based app, as its own settings should be separate than that of Edge browser's settings.

**Comment by MahdiGhiasi** [comment]
I agree that it *shouldn't* have to do anything, but it does. Disabling that breaks Xpo Music. Ask Microsoft ¯\_(ツ)_/¯

Anyway, regarding this issue, Can you please tell me if open.spotify.com works fine on Edge Legacy or not?

**Comment by Onoitsu2** [comment]
![image](https://user-images.githubusercontent.com/4420175/77938830-8831ec00-7273-11ea-8211-9a18a7d5f2aa.png)
This is what loads for that page. But this prompt in XpoMusic is intermittent, like right now it's working for me, but after anywhere from an hour, to several hours of music playing it will fail out to that image that started this thread.

If possible perhaps you can make a debug version that collects logs (or show me how to gather them manually if it already does), I'd be more than happy to run it and help you try to recreate the issue so it can be fixed for all.

**Comment by MahdiGhiasi** [comment]
Oh, yeah. I forgot. open.spotify.com is broken today for Edge. Xpo Music manually fixes that.

Xpo Music collects logs, you can send the logs from Settings -> Help -> contact me via email. Logs are attached to the email (you need to have Mail app as the default email app)

**Comment by Onoitsu2** [comment]
OK, quick question, do the logs reset each launch? If they do, I'd be unable to gather them, because cannot navigate anywhere in the app when that screen shows up, it takes up the entire page within the app.

**Comment by MahdiGhiasi** [comment]
No, they do not reset. The app always keeps the last ~10MB of logs data, if I remember correctly.
