### ISSUE TITLE
Name hidden behind window buttons

### ISSUE THREAD

**Issue by ajmeese7** [MahdiGhiasi/Xpotify#87]
![image](https://user-images.githubusercontent.com/17814535/77235664-d9602280-6b85-11ea-8baa-2bea00583207.png)

Since there is only part of a top bar, the content acts like there isn't one at all and sits behind the navigation buttons in the upper right.

**Comment by MahdiGhiasi** [comment]
This should be fixed in the recent over-the-air update.
