### ISSUE TITLE
XpoMusic no longer in Marketplace

### ISSUE THREAD

**Issue by abelsquidhead** [MahdiGhiasi/Xpotify#88]
Hi I'm a huge fan of XpoMusic and noticed it's no longer in the windows marketplace. Is it coming back? Is the the end for XpoMusic?

Thanks!

--a

**Comment by MahdiGhiasi** [comment]
Xpo Music will no longer be available on Microsoft Store. However, I'm working on bringing Xpo Music back via an standalone installer outside of the Store. Stay tuned.

**Comment by MisakaSakura** [comment]
@MahdiGhiasi So we have no method to install your app now?

**Comment by TotalChris** [comment]
@MahdiGhiasi The app should remain in the store until the standalone installer is finished. How are people going to download it?

**Comment by TotalChris** [comment]
Found the reason: https://mspoweruser.com/spotify-ask-microsoft-to-take-down-xpo-music-again/

**Comment by WolfganP** [comment]
Oops, I recently had to re-install my machine and couldn't find XPO anywhere; I know why now :-(
Is there any way to install offline currently? (or portable exe maybe?)

**Comment by MahdiGhiasi** [comment]
@WolfganP If you had previously downloaded Xpo Music from Store, you can still find it in "My Library" section of the Store and install it from there.

**Comment by WolfganP** [comment]
> @WolfganP If you had previously downloaded Xpo Music from Store, you can still find it in "My Library" section of the Store and install it from there.

Found it (never visited that section :-) Thanks for the tip!

**Comment by TotalChris** [comment]
@MahdiGhiasi could you provide an AppxPackage file for us to use in the meantime? I say this because I transferred my Microsoft accounts when reinstalling windows, so I don't technically have Xpo.

**Comment by MahdiGhiasi** [comment]
XpoMusic is now available again for download, get it at [XpoMusic.com](https://xpomusic.com/)
