### ISSUE TITLE
[Feature request] Plus/Minus for favourite next to each song in playlist

### ISSUE THREAD

**Issue by ziplock9000** [MahdiGhiasi/Xpotify#9]
Spotify shows a little plus/minus next to each song in a playlist if it's a favourite, thus a visual indicator at a glance for every song in the playlist. Clicking on it also toggles this state. 
Please duplicate this functionality on Windows Desktop.
EDIT: I've updated this to make it more clearly about the plus/minus next to songs listed in a playlist that allows you to make them a favourite with one click and also see at a glance the favourite state of every song in that playlist.

**Comment by omfgnuts** [comment]
There's ➕  instead of ❤️ i think
![image](https://user-images.githubusercontent.com/845482/59065886-70d5dc80-88b6-11e9-99b0-601b7da9c55b.png)
![image](https://user-images.githubusercontent.com/845482/59065935-8ba85100-88b6-11e9-991c-1cd561e83951.png)

**Comment by ziplock9000** [comment]
I'm not seeing that for songs in a playlist I'm looking at now. Just a heart for the entire playlist as a whole.
https://i.imgur.com/ObVHrUZ.png
I'm using the client v1.6.0.0

**Comment by raccube** [comment]
Interestingly enough I get plus/checkmark on desktop and hearts on mobile.

**Comment by pepijnmm** [comment]
when you play a song don't you see the heart on the left side?
![image](https://user-images.githubusercontent.com/3217184/59136909-74846480-8985-11e9-8deb-b8dbc7607394.png)
Also when I click on the three dots on the right of a song I get the option to add it to my favourites.(also on 1.6.0.0)
Or do you mean in a playlist in the table on the left of every song?
Spotify Windows version:
![image](https://user-images.githubusercontent.com/3217184/59137107-6420b980-8986-11e9-8845-730650473a13.png)

**Comment by ziplock9000** [comment]
I've updated my OP to make it more clear what I mean. Here's a random playlist / album. There are no hearts/plus/minus next to each song in the list. There is in Windows desktop Spotify however

Xpotify: 
<img width="682" alt="ApplicationFrameHost_2019-06-08_14-02-42" src="https://user-images.githubusercontent.com/5209752/59147635-1d6aa800-89f6-11e9-8833-6be752602c49.png">


Spotify: 
<img width="679" alt="NVIDIA_Share_2019-06-08_14-08-03" src="https://user-images.githubusercontent.com/5209752/59147719-e3e66c80-89f6-11e9-8358-6cf3c95e11e4.png">



Yes when you click on the 3 dots you can favourite, but that is not a visual indicator that you can see at a glance for the entire playlist like you can in Spotify. It's also several more clicks, which is actually important.

**Comment by MahdiGhiasi** [comment]
This is done and available in Xpo Music v2.0.

**Comment by ziplock9000** [comment]
Brilliant!
