### ISSUE TITLE
App is crashing when right clicking on a song bottom left the app

### ISSUE THREAD

**Issue by Mikey1993** [MahdiGhiasi/Xpotify#95]
As the title says.
When playing a song, and right clicking on the songs name to hope and get some useful options, you are getting a screen that says: "Something went wrong" and I am proposed with a sole option to reload the page.

P.S. resetting the app also doesn't help.

Attaching a picture:
![image](https://user-images.githubusercontent.com/8223772/82667554-bd8a0300-9c40-11ea-8c8b-21910577c428.png)

**Comment by MahdiGhiasi** [comment]
This happens on the Spotify PWA itself as well, seems to be a bug on their side.

**Comment by Mikey1993** [comment]
Not happening to me on their desktop UWP app.

**Comment by MahdiGhiasi** [comment]
Happens on their PWA (located on [open.spotify.com](https://open.spotify.com)), which Xpo Music is based on, on Chrome as well.
