### ISSUE TITLE
Ensure Secure Playback Issue

### ISSUE THREAD

**Issue by BetaBrainz** [MahdiGhiasi/Xpotify#97]
![image](https://user-images.githubusercontent.com/62415189/82979868-bb8bbf80-a005-11ea-8adb-7e9754975345.png)
I'm getting this error whenever i open xpomusic
I'm using **Edge Chromium (Dev)** and I have enabled the following settings..
![image](https://user-images.githubusercontent.com/62415189/82979994-04437880-a006-11ea-9231-e83da5eef139.png)
![image](https://user-images.githubusercontent.com/62415189/82980019-0f96a400-a006-11ea-83ef-58ad1067cda4.png)
Is there something i must change?

**Comment by MahdiGhiasi** [comment]
The current public version of Xpo Music is still based on legacy Edge, so you should enable "Media Licenses" setting in the Privacy & Security section of **Edge Legacy** settings.
